// Generated by CoffeeScript 1.6.3
(function() {
  var dynect;

  dynect = module.exports = {
    auth: require('./dynect/auth'),
    client: require('./dynect/client'),
    a_record: require('./dynect/a_record')
  };

}).call(this);
