// Generated by CoffeeScript 1.6.3
(function() {
  var ARecord;

  ARecord = (function() {
    function ARecord(zone, fqdn, client) {
      this.zone = zone;
      this.fqdn = fqdn;
      this.client = client;
    }

    ARecord.prototype.get = function(record_id, callback) {
      return this.client.get("ARecord/" + this.zone + "/" + this.fqdn + "/" + record_id, function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('ARecord get error'));
        } else {
          return cb(null, b);
        }
      });
    };

    ARecord.prototype.list = function(callback) {
      return this.client.get("ARecord/" + this.zone + "/" + this.fqdn, function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('ARecord list error'));
        } else {
          return cb(null, b);
        }
      });
    };

    ARecord.prototype.create = function(data) {
      return this.client.post("ARecord/" + this.zone + "/" + this.fqdn, rdata, function(err, s, b) {
        if (err) {
          return cb(err);
        }
        if (s !== 200) {
          return cb(new Error('ARecord create error'));
        } else {
          return cb(null, b);
        }
      });
    };

    return ARecord;

  })();

  module.exports = ARecord;

}).call(this);
