// Generated by CoffeeScript 1.6.3
(function() {
  var auth, qs, request;

  qs = require('querystring');

  request = require('request');

  auth = module.exports = {
    modes: {
      cli: 0
    },
    config: function(options) {
      if (options.customer && options.username && options.password) {
        this.mode = this.modes.cli;
      } else {
        throw new Error('No working mode recognized');
      }
      this.options = options;
      return this;
    },
    login: function(callback) {
      var options;
      if (this.mode === this.modes.cli) {
        options = {
          url: url.parse("https://api.dynect.net/REST/Session/"),
          method: 'POST',
          body: qs.stringify({
            customer_name: this.options.customer,
            user_name: this.options.username,
            password: this.options.password
          }),
          headers: {
            'Content-Type': 'application/json',
            'User-Agent': 'node-dynect/0.0.0 (https://github.com/myplanetdigital/node-dynect) terminal/0.0'
          }
        };
        return request(options, function(err, res, body) {
          if (err != null) {
            return callback(err);
          } else {
            try {
              body = JSON.parse(body);
            } catch (_error) {
              err = _error;
              callback(new Error('Unable to parse body'));
            }
            if (res.statusCode === 401) {
              return callback(new Error(body.message));
            } else {
              return callback(null, body.version, body.token);
            }
          }
        });
      } else {
        return callback(new Error('No working mode defined'));
      }
    }
  };

}).call(this);
