// Generated by CoffeeScript 1.6.3
(function() {
  var auth, qs, request, url;

  request = require('request');

  url = require('url');

  qs = require('querystring');

  auth = module.exports = {
    modes: {
      cli: 0
    },
    config: function(options) {
      if (options.customer && options.username && options.password) {
        this.mode = this.modes.cli;
      } else {
        throw new Error('No working mode recognized');
      }
      this.options = options;
      return this;
    },
    login: function(callback) {
      var options, params, uri;
      if (this.mode === this.modes.cli) {
        params = {
          customer_name: this.options.customer,
          user_name: this.options.username,
          password: this.options.password
        };
        uri = 'https://api.dynect.net/REST/Session?';
        uri += qs.stringify(params);
        options = {
          url: url.parse(uri),
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'User-Agent': 'node-dynect/0.0.0 (https://github.com/myplanetdigital/node-dynect) terminal/0.0'
          }
        };
        return request(options, function(err, res, body) {
          if (err != null) {
            return callback(err);
          } else {
            try {
              console.log(body);
              body = JSON.parse(body);
            } catch (_error) {
              err = _error;
              callback(new Error('Unable to parse body'));
            }
            if (res.statusCode === 400) {
              return callback(new Error(JSON.stringify(body.msgs)));
            } else {
              return callback(null, body.job_id, body.data.token);
            }
          }
        });
      } else {
        return callback(new Error('No working mode defined'));
      }
    }
  };

}).call(this);
