// Generated by CoffeeScript 1.6.3
(function() {
  var ARecord, Client, request, _class, _ref;

  request = require('request');

  ARecord = require('./a_record');

  Client = (function() {
    function Client() {
      _ref = _class.apply(this, arguments);
      return _ref;
    }

    _class = Client.token;

    Client.prototype.a_record = function() {
      return new ARecord(zone, fqdn, this);
    };

    Client.prototype.query = function(path) {
      var foo, uri;
      if (path == null) {
        path = '/';
      }
      if (path[0] !== '/') {
        path = '/' + path;
      }
      uri = "https://";
      uri += "api.dynect.com/REST" + path;
      switch (typeof this.token) {
        case "object":
          if (this.token.customer && this.token.username && this.token.password) {
            return foo = bar;
          }
          break;
        case "string":
          return foo = bar;
      }
    };

    Client.prototype.errorHandle = function(res, body, callback) {
      var err, _ref1;
      if (Math.floor(res.statusCode / 100) === 5) {
        return callback(new Error('Error ' + res.statusCode));
      }
      try {
        body = JSON.parse(body || '{}');
      } catch (_error) {
        err = _error;
        return callback(err);
      }
      if (body.message && res.statusCode === 422) {
        return callback(new Error(body.message));
      }
      if (body.message && ((_ref1 = res.statusCode) === 400 || _ref1 === 401 || _ref1 === 404)) {
        return callback(new Error(body.message));
      }
      return callback(null, res.statusCode, body, res.headers);
    };

    Client.prototype.get = function(path, callback) {
      var _this = this;
      return request({
        uri: this.query(path),
        method: 'GET',
        headers: {
          'User-Agent': "node-dynect/0.0.0 (https://github.com/myplanetdigital/node-dynect)"
        }
      }, function(err, res, body) {
        if (err) {
          return callback(err);
        }
        return _this.errorHandle(res, body, callback);
      });
    };

    Client.prototype.post = function(path, content, callback) {
      var _this = this;
      return request({
        uri: this.query(path),
        method: 'POST',
        body: JSON.stringify(content),
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': "node-dynect/0.0.0 (https://github.com/myplanetdigital/node-dynect)"
        }
      }, function(err, res, body) {
        if (err) {
          return callback(err);
        }
        return _this.errorHandle(res, body, callback);
      });
    };

    return Client;

  })();

}).call(this);
